import {biodiversity, convertToNum, isSpaceEmpty} from "./index";

export function runTests() {
    const divTest = `.....
.....
.....
#....
.#...`;

    const divTestN = convertToNum(divTest);
    const divTestR = biodiversity(divTestN);
    if (divTestR !== 2129920) {
        throw `Incorrect biodiversity fn : ${divTestR} =/= 2129920`;
    }

    const emptyTest = `.....
.....
.....
.....
.....`;
    const emptyTestN = convertToNum(emptyTest);
    const emptyTestR = isSpaceEmpty(emptyTestN);
    if (!emptyTestR) {
        throw `Should be empty`;
    }

    const emptyTest2 = `.....
.....
.....
.#...
.....`;
    const emptyTestN2 = convertToNum(emptyTest2);
    const emptyTestR2 = isSpaceEmpty(emptyTestN2);
    if (emptyTestR2) {
        throw `Should be nonempty`;
    }
}